# BASE UI
ColorColumn: '- color_column'
Conceal: ''
Cursor: 'color_highlight -'
CursorIM: ''
CursorColumn: 'color_lvl_5 color_lvl_0'
CursorLine: '- -'
CursorLineNr: 'color_highlight -'
Directory: 'color_lvl_2 -'
DiffAdd: 'color_lvl_0 color_highlight'
DiffChange: 'color_lvl_4 -'
DiffDelete: 'color_lvl_4 color_error'
DiffText: 'color_lvl_0 color_highlight'
ErrorMsg: 'color_error -'
VertSplit: 'color_lvl_0 -'
Folded: 'color_lvl_2 color_lvl_0'
FoldColumn: 'color_lvl_2 color_lvl_0'
SignColumn: '- -'
IncSearch: 'color_highlight color_bg'
LineNr: 'color_lvl_1 -'
MatchParen: 'color_lvl_4 color_lvl_0'
ModeMsg: 'color_lvl_3 -'
MoreMsg: 'color_lvl_3 -'
NonText: 'color_lvl_3 -'
Normal: 'color_fg -'
PMenu: 'color_lvl_2 color_lvl_0'
PMenuSel: '- color_lvl_4'
PmenuSbar: 'color_fg color_lvl_1'
PmenuThumb: 'color_fg color_lvl_4'
Question: 'color_lvl_3 -'
Search: 'color_lvl_5 color_lvl_1'
SpecialKey: 'color_lvl_3 -'
SpellBad: '- color_error'
SpellLocal: '- color_error'
SpellCap: '- color_error'
SpellRare: '- color_error'
StatusLine: ''
StatusLineNC: ''
TabLine: 'color_lvl_2 -'
TabLineFill: 'color_fg -'
TabLineSel: 'color_lvl_0 color_highlight'
Title: 'color_fg -'
Visual: 'color_lvl_0 color_selection'
VisualNOS: 'color_lvl_0 color_selection'
WarningMsg: 'color_error -'
WildMenu: 'color_lvl_0 color_highlight'
# BASE SYNTAX
Comment: 'color_comment -'
Constant: 'color_lvl_4 -'
String: '' # Constant
Character: '' # Constant
Boolean: '' # Constant
Number: '' # Constant
Float: '' # Constant
Identifier: 'color_lvl_4 -'
Function: '' # Identifier
Statement: 'color_lvl_1 -'
Conditional: '' # Statement
Repeat: '' # Statement
Label: '' # Statement
Operator: '' # Statement
Keyword: 'color_lvl_3 -' # Statement
Exception: 'color_highlight -' # Statement
PreProc: 'color_highlight -'
Include: '' # PreProc
Define: '' # PreProc
Macro: '' # PreProc
PreCondit: '' # PreProc
Type: 'color_lvl_2 -'
StorageClass: '' # Type
Structure: '' # Type
Typedef: '' # Type
Special: 'color_highlight -'
SpecialChar: '' # Special
Tag: 'color_lvl_1 -' # Special
Delimiter: 'color_lvl_2 -' # Special
SpecialComment: '' # Special
Debug: '' # Special
Underlined: ''
Ignore: ''
Error: ''
Todo: 'color_highlight -'

# Treesitter
'@annotation': ''
'@attribute': ''
'@boolean': '@Boolean'
'@character': ''
'@character.special': ''
'@comment': '@Comment'
'@conditional': '@Conditional'
'@constant': ''
'@constant.builtin': '@Constant'
'@constant.macro': ''
'@constructor': 'color_lvl_4 -'
'@debug': ''
'@define': ''
'@exception': '@Exception'
'@field': 'color_highlight -'
'@float': ''
'@function': '@Function'
'@function.builtin': ''
'@function.call': ''
'@function.macro': ''
'@include': '@Include'
'@keyword': '@Keyword'
'@keyword.function': '@Keyword'
'@keyword.operator': '@Keyword'
'@keyword.return': '@Keyword'
'@label': ''
'@method': 'color_highlight_dim -'
'@method.call': 'color_lvl_4 -'
'@namespace': ''
'@none': ''
'@number': ''
'@operator': '@Operator'
'@parameter': '@Type'
'@parameter.reference': ''
'@preproc': ''
'@property': 'color_highlight -'
'@punctuation.bracket': 'color_lvl_2 -'
'@punctuation.delimiter': 'color_lvl_2 -'
'@punctuation.special': '@Delimiter'
'@repeat': ''
'@spell': ''
'@storageclass': ''
'@string': '@String'
'@string.escape': ''
'@string.regex': ''
'@string.special': ''
'@symbol': ''
'@tag': '@Tag'
'@tag.attribute': 'color_highlight -'
'@tag.delimiter': '@Delimiter'
'@text': ''
'@text.danger': ''
'@text.emphasis': ''
'@text.environment': ''
'@text.environment.name': ''
'@text.literal': ''
'@text.math': ''
'@text.note': ''
'@text.reference': ''
'@text.strike': ''
'@text.strong': ''
'@text.title': ''
'@text.todo': '@Todo'
'@text.underline': ''
'@text.uri': ''
'@text.warning': ''
'@type': '@Type'
'@type.builtin': ''
'@type.definition': ''
'@type.qualifier': ''
'@variable': 'color_lvl_1 -'
'@variable.builtin': ''

# mhinz/vim-startify
StartifyBracket: 'color_highlight -'
StartifyFile: 'color_lvl_4 -'
# StartifyFooter: ''
# StartifyHeader: ''
# StartifyNumber: ''
StartifyPath: 'color_lvl_1 -'
# StartifySelect: ''
StartifySlash: 'color_lvl_3 -'
# StartifySpecial: ''
# StartifyVar: ''
startifySection: 'color_lvl_2 -'

# tpope/vim-fugitive
fugitiveHash: 'color_lvl_4 -'
fugitiveHelpTag: 'color_fg -'
fugitiveStagedModifier: 'color_lvl_3 -'
fugitiveSymbolicRef: 'color_highlight -'
fugitiveUnstagedHeading: 'color_error -'
fugitiveUnstagedModifier: 'color_lvl_3 -'
fugitiveUntrackedHeading: 'color_error -'
fugitiveUntrackedModifier: 'color_lvl_3 -'

#NERDTree
NERDTreeCWD: 'color_error -'
NERDTreeClosable: 'color_lvl_5 -'
NERDTreeDir: 'color_lvl_3 -'
NERDTreeDirSlash: 'color_highlight -'
NERDTreeLinkDir: 'color_lvl_5 -'
NERDTreeLinkFile: 'color_lvl_5 -'
NERDTreeOpenable: 'color_lvl_5 -'

# Agit
agitDiffAdd: 'color_highlight -'
agitDiffFileName: 'color_lvl_4 -'
agitDiffHeader: 'color_lvl_0 color_selection'
agitDiffRemove: 'color_error -'
agitHead: 'color_error color_lvl_5'
agitRef: 'color_highlight -'
agitRemote: 'color_lvl_4 -'
agitStatAdded: 'color_highlight -'
agitStatRemoved: 'color_error -'
agitTag: 'color_lvl_4 -'

# COC
CocListLine: 'color_lvl_0 color_selection'
CocListSearch: 'color_highlight -'
CocMenuSel: 'color_highlight color_lvl_1'

# kamykn/spelunker.vim
SpelunkerSpellBad: 'color_lvl_5 color_error'
SpelunkerComplexOrCompoundWord: 'color_lvl_5 color_error'
