---
# BASE UI
ColorColumn: "- color_column"
Conceal: "- -"
CurSearch: "color_bg color_highlight"
Cursor: "color_highlight -"
CursorIM: ""
CursorColumn: "color_lvl_5 color_lvl_0"
CursorLine: "- color_column"
CursorLineNr: "color_highlight -"
Directory: "color_lvl_2 -"
DiffAdd: "color_bg color_highlight"
"@diff.plus": "color_bg color_highlight"
DiffChange: "- -"
"diff.delta": "- -"
DiffDelete: "color_lvl_5 color_error"
"diff.minus": "color_lvl_5 color_error"
DiffText: "color_bg color_lvl_3"
EndOfBuffer: "- -"
ErrorMsg: "color_error -"
VertSplit: "color_lvl_0 -"
Folded: "color_lvl_2 color_lvl_0"
FoldColumn: "color_lvl_2 color_lvl_0"
SignColumn: "- -"
IncSearch: "color_bg color_highlight"
LineNr: "color_lvl_1 -"
MatchParen: "color_lvl_4 color_lvl_0"
ModeMsg: "color_lvl_3 -"
MoreMsg: "color_lvl_3 -"
NonText: "color_lvl_3 -"
Normal: "color_fg -"
PMenu: "color_lvl_3 color_lvl_0"
PMenuSel: "color_bg color_highlight"
PmenuSbar: "color_fg color_lvl_1"
PmenuThumb: "color_fg color_lvl_4"
Question: "color_lvl_3 -"
QuickFixLine: "- -"
Search: "color_lvl_5 color_lvl_1"
SpecialKey: "color_lvl_3 -"
SpellBad: "color_lvl_5 color_error"
SpellLocal: "color_lvl_5 color_error"
SpellCap: "color_lvl_5 color_error"
SpellRare: "color_lvl_5 color_error"
StatusLine: ""
StatusLineNC: ""
Syntax: "color_error -"
TabLine: "color_lvl_2 -"
TabLineFill: "color_fg -"
TabLineSel: "color_bg color_highlight"
# TermCursor: "- -"
# TermCursorNC: "- -"
# TermCurrentCursor: "- -"
# TermjobBg: "- -"
# TermjobFg: "- -"
Title: "color_fg -"
Visual: "color_lvl_0 color_selection"
VisualNOS: "color_lvl_0 color_selection"
WarningMsg: "color_error -"
WildMenu: "color_bg color_highlight"
# BASE SYNTAX
Boolean: "" # Constant
Character: "" # Constant
Comment: "color_comment -"
Conditional: "color_lvl_3 -" # Statement
Constant: "color_lvl_4 -"
Debug: "" # Special
Define: "" # PreProc
Delimiter: "color_lvl_2 -" # Special
Error: ""
Exception: "color_highlight -" # Statement
Float: "" # Constant
Function: "color_highlight -" # Identifier
Identifier: "color_lvl_4 -"
Ignore: ""
Include: "" # PreProc
Keyword: "color_lvl_2 -" # Statement
Label: "color_highlight -" # Statement
Macro: "" # PreProc
Number: "" # Constant
Operator: "color_lvl_2 -" # Statement
PreCondit: "" # PreProc
PreProc: "color_highlight -"
Repeat: "" # Statement
Special: "color_highlight -"
SpecialChar: "" # Special
SpecialComment: "" # Special
Statement: "color_lvl_1 -"
StorageClass: "" # Type
String: "@Constant"
Structure: "" # Type
Tag: "@Special"
Todo: "color_highlight -"
Type: "color_lvl_3 -"
Typedef: "" # Type
Underlined: "color_highlight - u"
ActiveWindow: "- color_bg"
InactiveWindow: "- color_column"

# Nvim/LSP
FloatTitle: "color_lvl_4 -"
LspReferenceRead: "color_lvl_3 color_lvl_0"
LspReferenceText: "color_lvl_3 color_lvl_0"
LspReferenceWrite: "color_lvl_3 color_lvl_0"
NormalFloat: "color_lvl_3 color_bg"

# Dressing
FloatBorder: "color_lvl_3 color_bg"

# Treesitter
"@annotation": "color_lvl_5 color_error"
"@attribute": "color_highlight -"
"@boolean": "@Boolean"
"@character": "color_lvl_5 color_error"
"@character.special": "color_error -"
"@comment": "@Comment"
"@conceal": "@Conceal"
"@conditional": "@Conditional"
"@keyword.conditional": "@Conditional"
"@constant": "@Constant"
"@constant.builtin": "@Constant"
"@constant.macro": "color_lvl_5 color_error"
"@constructor": "color_lvl_4 -"
"@debug": "color_lvl_5 color_error"
"@keyword.debug": "color_lvl_5 color_error"
"@define": "color_lvl_5 color_error"
"@exception": "@Exception"
"@keyword.exception": "@Exception"
"@field": "color_highlight -"
"@variable.member": "color_highlight -"
"@float": "@Float"
"@number.float": "@Float"
"@function": "@Function"
"@function.builtin": "@Function"
"@function.call": "color_lvl_5 -"
"@function.macro": "@Macro"
"@include": "@Include"
"@keyword.import": "@Include"
"@keyword": "@Keyword"
"@keyword.function": "@Keyword"
"@keyword.operator": "@Operator"
"@keyword.return": "color_lvl_3 -"
"@label": "@Label"
"@method": "color_highlight -"
"@function.method": "color_highlight -"
"@method.call": "color_lvl_5 -"
"@function.method.call": "color_lvl_5 -"
"@namespace": ""
"@module": ""
"@none": ""
"@number": "@Number"
"@operator": "@Operator"
"@parameter": "@Type"
"@variable.parameter": "@Type"
"@parameter.reference": "color_lvl_5 color_error"
"@preproc": "@PreProc"
"@keyword.directive": "@PreProc"
"@property": "color_highlight -"
"@punctuation.bracket": "color_lvl_2 -"
"@punctuation.delimiter": "color_lvl_2 -"
"@punctuation.special": "@Delimiter"
"@markup.list": "@Delimiter"
"@repeat": "@Conditional"
"@keyword.repeat": "@Conditional"
"@spell": ""
"@storageclass": "color_lvl_5 color_error"
"@keyword.storage": "color_lvl_5 color_error"
"@string": "@Constant"
"@string.escape": "color_highlight_dim -"
"@string.regex": "color_highlight_dim -"
"@string.regexp": "color_highlight_dim -"
"@string.special": "@String"
"@markup.link.label": "@String"
"@symbol": "color_lvl_3 -"
"@string.special.symbol": "color_lvl_3 -"
"@tag": "@Tag"
"@tag.attribute": "color_highlight -"
"@tag.delimiter": "@Delimiter"
"@text": ""
"@text.danger": "color_lvl_5 color_error"
"@text.emphasis": "color_lvl_4 color_bg i"
"@text.environment": "color_lvl_5 color_error"
"@text.environment.name": "color_lvl_5 color_error"
"@text.literal": "- color_lvl_0"
"@markup.raw": "- color_lvl_0"
"@text.math": "color_lvl_5 color_error"
"@text.note": "color_lvl_5 color_error"
"@text.reference": ""
"@markup.link": ""
"@text.strike": "color_lvl_5 color_error"
"@markup.strikethrough": "color_lvl_5 color_error"
"@text.strong": "color_lvl_4 color_bg b"
"@markup.strong": "color_lvl_4 color_bg b"
"@text.title": "@Title"
"@markup.heading": "@Title"
"@text.title.1": "color_lvl_5 - b"
"@text.title.1.marker": "color_highlight - b"
"@text.title.2": "color_lvl_4 - b"
"@text.title.2.marker": "color_highlight - b"
"@text.title.3": "color_lvl_3 - b"
"@text.title.3.marker": "color_highlight - b"
"@text.title.4": "color_lvl_2 - b"
"@text.title.4.marker": "color_highlight - b"
"@text.title.5": "color_lvl_1 - b"
"@text.title.5.marker": "color_highlight - b"
"@text.todo": "@Todo"
"@text.underline": "color_lvl_4 -"
"@text.uri": "color_highlight -"
"@markup.link.url": "color_highlight -"
"@string.special.url": "color_highlight -"
"@text.warning": "color_error -"
"@type": "@Type"
"@type.builtin": "@Type"
"@type.definition": "color_lvl_5 color_error"
"@type.qualifier": "color_lvl_4 -"
"@variable": "color_lvl_1 -"
"@variable.builtin": "color_lvl_1 -"

# mhinz/vim-startify
# StartifyFooter: ''
# StartifyHeader: ''
# StartifyNumber: ''
# StartifySelect: ''
# StartifySpecial: ''
# StartifyVar: ''
StartifyBracket: "color_highlight -"
StartifyFile: "color_lvl_4 -"
StartifyPath: "color_lvl_2 -"
StartifySlash: "color_highlight -"
startifySection: "color_lvl_2 -"

# tpope/vim-fugitive
diffAdded: "color_highlight -"
diffChanged: "color_lvl_4 -"
diffRemoved: "color_error -"
fugitiveCount: ""
fugitiveHash: "color_lvl_4 -"
fugitiveHeader: "@Label"
fugitiveHelpTag: "color_fg -"
fugitiveSection: ""
fugitiveStagedModifier: "color_lvl_3 -"
fugitiveStagedSection: ""
fugitiveSymbolicRef: "color_lvl_4 -"
fugitiveUnstagedHeading: "color_error -"
fugitiveUnstagedModifier: "color_lvl_4 -"
fugitiveUnstagedSection: ""
fugitiveUntrackedHeading: "color_error -"
fugitiveUntrackedModifier: "color_lvl_4 -"

FugitiveblameDelimiter: "color_lvl_4 -"
FugitiveblameNotCommittedYet: "color_error -"
FugitiveblameShort: "color_highlight -"
FugitiveblameTime: "color_lvl_4 -"
FugitiveblameUncommitted: "color_error -"

# NERDTree
NERDTreeCWD: "color_lvl_2 -"
NERDTreeClosable: "color_highlight -"
NERDTreeDir: "color_lvl_2 -"
NERDTreeDirSlash: "color_highlight -"
NERDTreeExecFile: "color_highlight -"
NERDTreeFile: "color_lvl_4 -"
NERDTreeLinkDir: "color_lvl_3 -"
NERDTreeLinkFile: "color_lvl_1 -"
NERDTreeLinkTarget: "color_highlight -"
NERDTreeOpenable: "color_lvl_2 -"

# nvim-tree
NvimTreeSymlink: "color_lvl_4 -"
NvimTreeExecFile: "color_highlight -"
NvimTreeSpecialFile: "color_error -"
NvimTreeOpenedFile: "color_error -"
NvimTreeCopiedHL: "color_lvl_0 color_highlight"
NvimTreeCutHL: "color_lvl_4 color_error"
NvimTreeModifiedFile: "color_highlight -"
NvimTreeRootFolder: "color_error -"
NvimTreeGitDirty: "color_highlight -"
NvimTreeGitNew: "color_error -"

# Agit
agitDiffAdd: "color_highlight -"
agitDiffFileName: "color_lvl_4 -"
agitDiffHeader: "color_lvl_0 color_selection"
agitDiffRemove: "color_error -"
agitHead: "color_error color_lvl_5"
agitRef: "color_highlight -"
agitRemote: "color_lvl_4 -"
agitStatAdded: "color_highlight -"
agitStatRemoved: "color_error -"
agitTag: "color_lvl_4 -"

# COC
CocListLine: "color_lvl_0 color_selection"
CocListSearch: "color_highlight -"
CocMenuSel: "color_highlight color_lvl_1"
CocSearch: "color_highlight -"

# kamykn/spelunker.vim
SpelunkerComplexOrCompoundWord: "color_lvl_5 color_error"
SpelunkerSpellBad: "color_lvl_5 color_error"

# qf
qfFileName: "color_lvl_4 -"
qfLineNr: "color_highlight -"
qfSeparator: "color_error -"

# Telescope
TelescopeSelection: "color_lvl_4 color_lvl_0"

# Mason
MasonError: "color_error -"
MasonHeader: "color_highlight -"
MasonHeaderSecondary: "color_highlight -"
MasonHeading: "color_highlight -"
MasonHighlight: "color_highlight -"
MasonHighlightBlock: "color_bg color_selection"
MasonHighlightBlockBold: "color_bg color_highlight b"
MasonHighlightBlockBoldSecondary: "color_bg color_highlight b"
MasonHighlightBlockSecondary: "color_bg color_selection"
MasonHighlightSecondary: "color_highlight -"
MasonLink: "- color_lvl_3 u"
MasonMuted: ""
MasonMutedBlock: "color_bg color_selection"
MasonMutedBlockBold: "color_bg color_selection b"
MasonNormal: "color_lvl_4 color_bg"

# LSP Signature
LspSignatureActiveParameter: "color_highlight -"

# Gitsigns
GitSignsCurrentLineBlame: "color_comment -"

GitSignsAdd: "color_highlight -"
GitSignsAddNr: "color_bg color_highlight"
GitSignsChange: "color_lvl_3 -"
GitSignsChangeNr: "color_bg color_lvl_3"
GitSignsChangedelete: "color_error -"
GitSignsChangedeleteNr: "color_bg color_error"
GitSignsDelete: "color_error -"
GitSignsDeleteNr: "color_lvl_3 color_error"
GitSignsTopdelete: "color_error -"
GitSignsTopdeleteNr: "color_lvl_3 color_error"

# todo-comments
DiagnosticInfo: "color_highlight -"

# vim-spectre
SpectreUI: "color_highlight -"
SpectreDiffChange: "color_lvl_5 color_error"
SpectreDiffDelete: "color_bg color_highlight"

# neorg
"@neorg.markup.bold": "color_lvl_4 color_bg b"
"@neorg.markup.verbatim": "- color_lvl_0"
"@neorg.links.file": "color_highlight -"
"@neorg.links.description": "color_lvl_4 -"
"@neorg.todo_items.done": "color_highlight color_bg b"
"@neorg.todo_items.pending": "color_fg color_bg b"
"@neorg.todo_items.on_hold": "color_neo_yellow color_bg b"
"@neorg.todo_items.urgent": "color_error color_bg b"
"@neorg.todo_items.cancelled": "color_lvl_4 color_bg b"
"@neorg.todo_items.recurring": "color_cerulean color_bg b"
"@neorg.tags.ranged_verbatim.begin": "color_lvl_0 -"
"@neorg.tags.ranged_verbatim.end": "color_lvl_0 -"
"@neorg.tags.ranged_verbatim.parameters": "color_lvl_0 -"
"@neorg.tags.ranged_verbatim.name.word": "color_lvl_0 -"

# blankline
"IblIndent": "color_lvl_0 -"

# cucumber
"cucumberUnparsed": "color_lvl_4 -"
"cucumberGiven": "color_highlight -"
"cucumberWhen": "color_highlight -"
"cucumberThen": "color_highlight -"
"cucumberAnd": "color_highlight -"
"cucumberGivenRegion": "color_lvl_1 -"
"cucumberWhenRegion": "color_lvl_2 -"
"cucumberThenRegion": "color_lvl_3 -"
"cucumberWhenTable": "color_cerulean -"
"cucumberThenTable": "color_cerulean -"
"cucumberWhenAndRegion": "color_lvl_5 -"
"cucumberThenAndRegion": "color_lvl_5 -"
